### ISSUE TITLE
Clicking and incrementing an emoji changes the width of the button

### ISSUE THREAD

**Issue by ChristofLee** [the-heap/Emojions#41]
## Detailed Description
When an emoji is clicked, it increments the number and also adjusts the width of the button. Flexbox tries to accommodate this and adjusts the width.

This is caused by `flexbox` and was introduced with adaptive styling #37.

## Possible Implementation
May require padding or a min-width on the content of `.emojion__single`.

**Comment by teesloane** [comment]
Good catch @ChristofLee; I was playing around with this as well now that the incrementEmoji works. I think min-width will fix this; but maybe we can make the adaptive styling work in a way that the min width changes based on the number of digits in the count (ie, 0, 10, 100, 1000)

**Comment by venomnert** [comment]
I was playing around with the styling and I tried changing the width from auto to 16% on the .emojion__single class. By doing so we give a fluid width for each emojion that is large enough to accommodate the number and the emoji. Here is what the final class would look like :

`.emojion__single {
    /* width: auto; */
    width: 16%;
}  `

**Comment by teesloane** [comment]
Interesting. Maybe you could post a screenshot or a gif? 

I think having a very specific size like 16% could be problematic on mobile devices however... do you think you could try using `min-width` and a pixel amount? 

If we combined `min-width` with some `@media-queries` we could probably solve this issue.

**Comment by venomnert** [comment]
Hey Tyler, here is gif of me changing the width from auto to 16%. It was also seem to work fine on mobile.
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/6043697/26039087/1ab60164-38e4-11e7-8b6d-53435b81640a.gif)

**Comment by teesloane** [comment]
Hey @venomnert thanks for sending a gif. We had a contributor just [merged a pr](https://github.com/the-heap/Emojions/pull/46) that managed to fix the problem using flex box - which is ideal because it uses the same styling methodology that the containers use..

I think that the 16% could have worked, although I think it limits the size on mobile — where before the emojis would stay centered and still span a full width, which might be ideal. Personally, I try and avoid using hard set percentage values whenever possible because there are so many different devices / screens making it difficult to gauge what'll happen at `x%` beyond our own devices.

Thanks for making a gif of your screen though — it makes it a lot easier to see / understand what's happening!!

**Comment by venomnert** [comment]
Hey I just read @broneks solution to the problem and it makes a lot of sense. I agree with the idea of sticking to the same methodology.
