### ISSUE TITLE
Pipe backend

### ISSUE THREAD

**Issue by quietcoding** [the-heap/Emojions#43]
Let me know if I've correctly or incorrectly opened an issue btw.

Backend:
- [x] Install json-server --> completed through npm install from package.json
- [ ] Add documentation on how to run json-server as backend
- [x] Added package.json dependency for build 
- [x] Create a mock database for emojion bar

Frontend:
- [ ] Get / Post functionality to backend db
- [ ] Update when emoji is clicked
- [ ] Asynchronous pipeline

Example of mockdata here:
![image](https://cloud.githubusercontent.com/assets/7574432/26022174/d9782520-376b-11e7-8cfd-e45e2f44dbd1.png)
Unique values will based off of it's "id" value

**Comment by teesloane** [comment]
Great work! Think you could make a pull request for this stuff?!

Something tells me that instead of just getting an array of objects back we will need an object of objects... so for example:

```
a_specific_emojion_mount_id: {
  "🐰" : 4,
  "✨ : 30,
  "🤖 : 13,
  ... etc 
},

another_emojion_mount : {...}

```

Does that make sense? It's late where I am, and I might just be missing somethign entirely. Perhaps the data structure has to be even more nested ...

**Comment by quietcoding** [comment]
Yea, it makes sense, I think I was over thinking it and wanted something like an id tied to objects. 

I don't see a reason for a more nested data structure, keeping it simple with objects tied to numerical seems best :). It's late here too, but it's the only time I have aside from a full time job haha.

**Comment by teesloane** [comment]
I know what you mean. Thanks for sharing some of your time on this project. 

I also agree with you about a simple data structure. Feel free to make a PR whenever you are happy with your work (finished or unfinished) and I'll be happy to look it over.

**Comment by quietcoding** [comment]
For sure, I shouldn't have made this issue so big then haha. I'll keep you posted.

Was this what you were thinking of by the way?

![image](https://cloud.githubusercontent.com/assets/7574432/26022509/5d141d4a-3775-11e7-9021-156b410233d9.png)

If so, this can be our mock database. I just need to somehow tie this to the front-end functions which will update to the database json as needed.

**Comment by teesloane** [comment]
This is looking good. 

I think one thing to keep in mind is that what's coming from the DB can nicely fit into the empty state struct waiting to be filled:

```js
  // State to pass through function pipeline
  var state = {
    dom: {
      mounts: [],
      containers: []
    },
    emojis: {}
  };

```

Ideally, it will eventually populate to look like this:

<img width="644" alt="screenshot 2017-05-13 00 53 06" src="https://cloud.githubusercontent.com/assets/12987958/26022567/b95964e2-3776-11e7-92f2-4ded442093af.png">

which I just pulled from the state object in the dom after going through the function pipe. 

So, instead of the backend returning an array of objects it probably should be an object of objects, where the `id` that you've written there is actually the _key_ for each emoji set. Does that make sense?

**Comment by quietcoding** [comment]
Ah, I think I understand. So essentially the ID will be our key, and there will be another object inside the object to store the values of the emojis like so?

![image](https://cloud.githubusercontent.com/assets/7574432/26022638/58723878-3778-11e7-96b0-c00d2a9f5f1b.png)
I didn't think too far ahead about how it would be tied to the state on the front-end. Good catch.
If this looks good, I'll begin figuring out the GET/PUT interface next.

**Comment by teesloane** [comment]
@qazqwezxc I think you're on the right track. So in the case of your screenshot, eventually `id` will be replaced with a very unique id that actually lines up with the user's mount in the dom. 

I'm going to review your PR shortly and hopefully merge it in this morning !

Thanks for your hard work @qazqwezxc ; I will make you a contributor to the project so that you can self-assign any other issues you're interested in as well

**Comment by teesloane** [comment]
<img width="589" alt="screenshot 2017-05-13 08 36 32" src="https://cloud.githubusercontent.com/assets/12987958/26025508/54811e84-37b7-11e7-923d-f973834e7257.png">

Great Work @qazqwezxc ! I added an npm script so that any one can launch the backend with `npm run dev`. Eventually I might add a way to pop open the `example.html` page automatically when that happens as well...

Any chance you have a twitter where the heap can thank you for your hard work? 🐦  🎉 . Would love to post that we have a dev api up now!

**Comment by quietcoding** [comment]
Thanks @teesloane,

I'm not huge on twitter, but you can find me @andrew_hoang (not very discrete, I know). 

Moving forwards, lets start looking at how we can tie this into the emojion front and back end system. The easiest method I've come up with so far is to utilize jQuery. We can use jQuery to post a GET request and check the local JSON database as shown by the code snippet below:

![image](https://cloud.githubusercontent.com/assets/7574432/26039826/44a027d0-38ed-11e7-8cf8-7c6681510489.png)

A small caveat was that I pulled the jQuery from a CDN (content distributed network). Should we choose to keep this locally, that may be another option too :). 

![image](https://cloud.githubusercontent.com/assets/7574432/26039840/72cba13e-38ed-11e7-814d-7aa4eb881f2a.png)

Let me know what you think. If you like what you're seeing, I can tie this to the incrementEmojiCount() function and whatever other function to track the emoji database.

Edit:
Pseudo code:
- Pull db.json local data. See if id for emojion bar exists
- if id does not exist, make one
- increment emoji used
- POST into db.json

**Comment by teesloane** [comment]
Hey @qazqwezxc - this is great. I can jot down a couple quick thoughts.
>  If you like what you're seeing

I do! 🎉 

> Jquery

I recommend using [Fetch](https://github.com/github/fetch) since we're just making network requests. Jquery comes with a lot of other functionality and is also a bit large. One of my goals is to keep the size of our snippet as small and unintrusive as possible since it's being embedded into possible already large sites. I think it's best if we try and stay as close to "vanilla" javascript as possible so that there are less dependencies and overall a smaller code size. (Fetch is native to chrome... and hopefully soon enough all browsers?)

>  I can tie this to the incrementEmojiCount() 

I have no idea how we're going to do this still. I think what you're describing has us on the right track, however. Also, I've talked with @gilbertkennen A bit about how we need to have this figured out so we can get the emoji picker client app (the thing written in elm) to work properly. 

Great work! 

Edit:

Just read over your pseudocode (good idea to write that out; def helps me ). I think what you have sounds good. I'm imagine we'll run into some edge cases and interesting catches with how we might setup our api/db but let's start with what something as simple as possible and then catch those cases if they should come up.

**Comment by quietcoding** [comment]
Hey @teesloane,

Ah, noticed your edit to fetch() recommendation. I definitely wholeheartedly agree, simpler is better if it's supported natively for chrome (chrome is awesome). I can create an early prototype by tomorrow night, but we should settle on a prototype solution for where to fetch our db.json POST/GET data.

I'll keep a close eye on where the client api goes from here and will adjust for future changes if what we have in snippet should be moved over in the coming days.

Edit: 
For now, if I create a pull request, it will most likely be a network fetch() from db.json and into the incrementEmojiCount() function. That way, it'll poll the data from the database after every click.

Cheers,
Andrew H

**Comment by teesloane** [comment]
Hey @qazqwezxc ,

That sounds great all around. For now we can increment our progress step by step as best as possible. I agree that it'll be important to settle on a prototype solution with a fetch to our dummy db.

Ideally, if we can stub out our network requests to the db.json... we should, (if we prototype successfully) be able to swap out `db.json` with a database without too much extra work (we'll need to _set up the db and an ORM likely_ but yeah, the request from the snippet shouldn't be too bad).\

Also, we will need to decide which language to write the back end in. Since the back end should be relatively simple (only one or two REST endpoints? ) then it's possible that we could offer up a chance to try a new language for this. Originally I thought of just using node, but perhaps it would be good to use any of the following : python, go, elixir, ... any suggestions??

**Comment by quietcoding** [comment]
They all sound like awesome suggestions @teesloane,

We could give a go at Node or Python (ExpressJS and Flask are nice and lightweight). Rather than pick and choose an backend framework, I think this could be an opportunity to explore possible frameworks for those who are interested.

Go -> Great for high concurrency, non-blocking pipelines
Elixir -> Same as Go
Python -> Flask ease of use
NodeJS -> ExpressJS, painless transition from front to back end code

I haven't had enough time to investigate the various pros and cons of them, and if we hope to meet our end-of-month deadline, I would suggest using either ExpressJS for ease of use (though I've never used it before) OR Python-Flask for simple syntax. Django or any other monolithic would go against this project as you intended and would increase complexity unnecessarily. That's just my 2 cents.

P.S if someone is willing to look into Elixir or Go, you're more than welcome since they're new to me as well and sound pretty cool.

If this hasn't been fully tackled by anyone else, I should have a solution by Wed/Thurs depending on my schedule hopefully!

**Comment by teesloane** [comment]
@qazqwezxc Excellent points and summaries on the difference langs. I have experience with both Flask and Express, and a bit of Go.

Go seems to be a bit more handrolled than some of the other solutions, and I really don't know much about elixir; althought there's a chance it will be used in the next project. 

Regarding the end of month deadline — that's a soft deadline in that the project will still exist and people can still contribute, but The Heap will eventually start a new project to bring more people in, with more focus on the current project at the moment. 

I'm starting to lean towards flask for both simplicity and for the fun of having a new language (can attract more contributors) as well as encourage people to learn new stuff. Thoughts?

**Comment by quietcoding** [comment]
Yea, very valid points. I think flask would be great for getting a prototype up and running and adding on libraries as needed. Lets get this done :). 

I'm interested in seeing how elixir may be used in the future heap projects and where we can take it.

Good vibes overall.
- Andrew H

**Comment by teesloane** [comment]
Alright, flask it is; I'm going to start creating some issues for this!

edit: I created some issues; might just be worth starting at the (new!) roadmap for our API: #54
