### ISSUE TITLE
Feedback for this project. 

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#58]
Read This to:
- Help provide feedback on how The Heap Runs Projects.

What I expect you to know / have done:
- If you have contributed in some way to this project (in _any_ way; not just coding) I would love to hear your feedback.

---

I could use your feedback. Help me make the next The Heap project easier to get started and more fun. Feel free to post any thoughts here; if nothing comes to mind immediately here are some prompts:

## Prompts

- How easy was it to get started contributing?
- What was the most intimidating thing about this repo? 
- What was the most exciting thing about this project?
- Do you feel like your contributions were recognized well? What could be better?
- Were the roadmaps useful? Should there be just one single road map for all parts of a project?
- Would live pair programming be useful (like with screenhero or a similar tool?) What about live code streams? 
- Did you watch The Heap videos? were they useful? What about twitter — have you followed [The Heap](https://twitter.com/theheap_) and if so, was it useful / informative? 

Tagging all you lovely contributors for your thoughts. @ericbastarache @mihok  @hyperwidget  @broneks  @gilbertkennen  @ChristofLee

**Comment by quietcoding** [comment]
How easy was it to get started contributing?
Decently easy, a bit intimidating since I have the fear that I'm wasting time working on a piece of code someone else may already be working on.

What was the most intimidating thing about this repo?
Understanding the languages used to get the code up and running. The front-end toolsuite is ridiculous these days with changing tech every 6 months.

What was the most exciting thing about this project?
Feeling accountable, having a commitment to an open source project people (decently) care about.

Do you feel like your contributions were recognized well? What could be better?
I have commitment issues to projects like these haha. I find it a bit difficult to stay committed to tasks.

Did you watch The Heap videos? were they useful? What about twitter — have you followed The Heap and if so, was it useful / informative?
No, I did not watch The Heap videos, too long, maybe skimmed over what I needed to see and what was going through your thought process as you pieced the code together. 
No, I don't use twitter, haven't been a big fan of twitter since it's inception.

Side note: I joined this project because of @mackiedrew since it was a way for me to keep track of my programming/technical skills outside of the workplace. Met him, and was inspired to try out new things.

**Comment by teesloane** [comment]
@qazqwezxc Thanks for adding your thoughts! Really appreciate it; and it'll help me shape these projects going forward.

I can definitely sympathize with your thoughts on front end code haha. 

Make commitments is hard; but important especially if when worrying that someone else might be working on the same code. I'm not sure what the solution is for that. I think being on the github issue for the task and commenting frequently / using the gitter chat to help out could be the best way. Not sure what the solution would be.

also @qazqwezxc what are your thoughts on pair programming? Would you benefit from doing that using something like screen hero to work on an issue collaboratively?

**Comment by quietcoding** [comment]
I 'tweeted' a while back to The Heap and not sure if you received it, but I suggested we have an open slack channel for this project. It would make it easier for real-time feedback on everyone's thoughts going about various issues IMO.

**Comment by teesloane** [comment]
Ah dang I didn't see it. @qazqwezxc as for an open chat - I originally tried ourtslack but it's not very well suited to open communities; users have to be manually invited or programmatically; it seems more beneficial for business teams with set amounts of users. I'm not sure if you've seen out gitter channel but it integrates well with github (anyone who is a github user can join the chat; issues are nicely linked etc)... [check it out!](https://gitter.im/the-heap/Lobby)

with that said, everyone seems to have slack; so people tend not to mind having yet another slack channel to chat on. Do you think it might be worth it to go over to slack for that reason alone ? I'm unsure.

**Comment by quietcoding** [comment]
Ahh, when you said gitter, I thought you meant Github. OK it all makes sense now. 

Pair programming would probably be fun, we would have to experiment and see how it goes :)
